//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAProgramOnlineIdeApi.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LadderProgramResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LadderProgramResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IAProgramOnlineIdeApi.Resource.LadderProgramResource", typeof(LadderProgramResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;name&quot;:&quot;(User defined)&quot;,&quot;displayName&quot;:&quot;(User defined)&quot;,&quot;isEnabled&quot;:false,&quot;instructions&quot;:[0]},{&quot;name&quot;:&quot;Rung/Branch&quot;,&quot;displayName&quot;:&quot;Rung/Branch&quot;,&quot;isEnabled&quot;:true,&quot;instructions&quot;:[1,2,15]},{&quot;name&quot;:&quot;Bit&quot;,&quot;displayName&quot;:&quot;Bit&quot;,&quot;isEnabled&quot;:true,&quot;instructions&quot;:[3,4,5,6,7,8,9,10,11,12,79,138]},{&quot;name&quot;:&quot;Program Control&quot;,&quot;displayName&quot;:&quot;Program Control&quot;,&quot;isEnabled&quot;:true,&quot;instructions&quot;:[13,14,33,127,146,170,171,175]},{&quot;name&quot;:&quot;Math&quot;,&quot;displayName&quot;:&quot;Math&quot;,&quot;isEnabled&quot;:true,&quot;instructions&quot;:[16,17,18,19,28,118,126,182]},{&quot;name [rest of string was truncated]&quot;;.
        /// </summary>
        public static string categories {
            get {
                return ResourceManager.GetString("categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] categories_indented {
            get {
                object obj = ResourceManager.GetObject("categories_indented", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;name&quot;: &quot;2080-LC20-20AWB&quot;,
        ///    &quot;revisions&quot;: [ 6, 7, 8, 9, 10, 11, 12 ]
        ///  },
        ///  {
        ///    &quot;name&quot;: &quot;2080-LC20-20QBB&quot;,
        ///    &quot;revisions&quot;: [ 6, 7, 8, 9, 10, 11, 12 ]
        ///  },
        ///  {
        ///    &quot;name&quot;: &quot;2080-LC20-20QWB&quot;,
        ///    &quot;revisions&quot;: [ 6, 7, 8, 9, 10, 11, 12 ]
        ///  },
        ///  {
        ///    &quot;name&quot;: &quot;2080-LC30-10QVB&quot;,
        ///    &quot;revisions&quot;: [ 6, 7, 8, 9, 10, 11, 12 ]
        ///  },
        ///  {
        ///    &quot;name&quot;: &quot;2080-LC30-10QWB&quot;,
        ///    &quot;revisions&quot;: [ 6, 7, 8, 9, 10, 11, 12 ]
        ///  },
        ///  {
        ///    &quot;name&quot;: &quot;2080-LC30-16AWB&quot;,
        ///    &quot;revisions&quot;: [ 6, 7, 8, 9, 1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string deviceCatalog {
            get {
                return ResourceManager.GetString("deviceCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] deviceCatalog_indented {
            get {
                object obj = ResourceManager.GetObject("deviceCatalog_indented", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;id&quot;:0,&quot;name&quot;:&quot;UserDefinedInstruction&quot;,&quot;displayName&quot;:null,&quot;searchKeywords&quot;:[],&quot;tooltip&quot;:null,&quot;isEnabled&quot;:true,&quot;isShowImage&quot;:false,&quot;isDefaultFavorite&quot;:false},{&quot;id&quot;:1,&quot;name&quot;:&quot;rungs&quot;,&quot;displayName&quot;:&quot;Rung&quot;,&quot;searchKeywords&quot;:[],&quot;tooltip&quot;:&quot;Rung&quot;,&quot;isEnabled&quot;:true,&quot;isShowImage&quot;:true,&quot;isDefaultFavorite&quot;:true},{&quot;id&quot;:2,&quot;name&quot;:&quot;branches&quot;,&quot;displayName&quot;:&quot;Branch&quot;,&quot;searchKeywords&quot;:[&quot;branches&quot;,&quot;BST&quot;,&quot;NXB&quot;,&quot;BND&quot;],&quot;tooltip&quot;:&quot;Branch&quot;,&quot;isEnabled&quot;:true,&quot;isShowImage&quot;:true,&quot;isDefaultFavorite&quot;:true},{&quot;id&quot;:3,&quot;name&quot;:&quot;direct_contact&quot;, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string instructions {
            get {
                return ResourceManager.GetString("instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] instructions_indented {
            get {
                object obj = ResourceManager.GetObject("instructions_indented", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
